version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: intentra_db
    restart: always
    environment:
      POSTGRES_USER: intentra_user
      POSTGRES_PASSWORD: intentra_pass
      POSTGRES_DB: intentra_db
    ports:
      - "5432:5432"
    volumes:
      - intentra_pgdata:/var/lib/postgresql/data

volumes:
  intentra_pgdata: